language: node_js
node_js:
- 8.0.0
cache:
  directories:
  - node_modules
script:
  - npm test
  - CI=false npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  on:
branch: master