language: node_js
node_js:
- 8.11.4
cache:
  directories:
  - node_modules
script:
  - npm test
- npm start


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  on:
branch: master